### ISSUE TITLE
Improve throughput statistics with Fiberblaze adapters

### ISSUE THREAD

**Issue by cardigliano** [ntop/n2disk#13]
Statistics in /proc/net/pf_ring/stats/* for each interval show throughput of an arbitrary amount (a spike, then back to 0.00Mpps and 0.00Gbps). The dumpedBytes counter reliably increments but the throughput doesn't.  
Note: at the moment n2disk computes packets/bytes in the capture loop in packet mode only, while in segment mode (which is what Fiberblaze uses) statistics are read from the adapter to avoid scanning all segments. This seems to cause this issue (it seems statistics are not constantly updated by the adapter, this need to be verified).

**Comment by cardigliano** [comment]
This seems to work in our lab, it is likely it depends on the Fiberblaze card model or driver (waiting for more details from the customer)

**Comment by nathandau** [comment]
This can be closed off. We have decided to use N2disk ZMQ monitoring instead. Thanks

**Comment by cardigliano** [comment]
Ok, we are not able to reproduce this thus I will close this for now.
