### ISSUE TITLE
[n2disk10g] machine parsable log format

### ISSUE THREAD

**Issue by JeremyAshton-shopify** [ntop/n2disk#2]
We are interested in performance and health monitoring of the individual services.  Unfortunately the log format for multithreaded capture is multiline.  Any chance we could have a feature added to support json?

```
19/Oct/2016 19:24:52 [n2disk.c:863] Proc Stats:
Duration:         0:00:46:42:420
Throughput:       <redacted> Mpps   <redacted> Gbps
Packets:          <redacted>
Filtered:         <redacted>
Dropped:          <redacted>
Bytes:            <redacted>
DumpedBytes:      <redacted>
DumpedFiles:      <redacted>
SlowSlavesLoops:  <redacted>
SlowStorageLoops: <redacted>
```

**Comment by cardigliano** [comment]
Is this still required? IMHO the current format can be easily parsed, however we can add an option to export stats in JSON format if needed.
