### ISSUE TITLE
Index location support with disk-limit option

### ISSUE THREAD

**Issue by jblokhuis** [ntop/n2disk#24]
It seems that the disk-limit parameter ignores the -I parameter when specified.

### Without disk-limit enabled:
n2disk -i zc:enp101s0f0 -I/index/enp101s0f0 -o /pcap -A /timeline/enp101s0f0  -b 8192 -p 1024 -S 0 -c 1 -w 2 -z 3,4,5 -Z -v
 
13/Mar/2020 11:27:19 [n2disk.c:2900]                   [writer][#0] Creating pcap file [idx 1] **_/pcap/30.pcap_**
13/Mar/2020 11:27:20 [n2disk.c:2970]                   [writer][#0] Creating index file _**/index/enp101s0f0/30.pcap.idx**_
 
### With disk-limit enabled:
n2disk -i zc:enp101s0f0 -I/index/enp101s0f0 -o /pcap -A /timeline/enp101s0f0  -b 8192 -p 1024 -S 0 -c 1 -w 2 -z 3,4,5 -Z -6 4098 -v
 
13/Mar/2020 11:31:47 [n2disk.c:2900]                   [writer][#0] Creating pcap file [idx 1] _**/pcap/1584095503.310082/1584095505.344544.pcap**_
13/Mar/2020 11:31:48 [n2disk.c:2970]                   [writer][#0] Creating index file _**/pcap/1584095503.310082/1584095505.344544.pcap.idx**_

**Comment by cardigliano** [comment]
@jblokhuis this has been fixed in n2disk dev and will be available with the next nightly build, please let me know if it works for you. Thank you.
