### ISSUE TITLE
n2disk cannot lock memory in a container

### ISSUE THREAD

**Issue by abedhossainn** [ntop/n2disk#34]
hello everyone.

i just started using licensed ntop products. the ntop and nprobe service is running on my system smoothly. but i'm unable to start n2disk. the log is showing **WARNING: Unable to lock memory [Cannot allocate memory]**
can anyone help me with the issue.

![image](https://user-images.githubusercontent.com/74364595/99346386-b6297680-28be-11eb-8209-a1e47d6ce1fa.png)

**Comment by cardigliano** [comment]
How much memory do you have on this system? Please provide "free" or "cat /proc/meminfo"

**Comment by abedhossainn** [comment]
> How much memory do you have on this system? Please provide "free" or "cat /proc/meminfo"

![image](https://user-images.githubusercontent.com/74364595/99367684-7b3a3980-28e4-11eb-8471-ee477bea1328.png)

**Comment by cardigliano** [comment]
You have 16MB of available memory, which is too little for dumping PCAP data.. what system is this?

**Comment by abedhossainn** [comment]
> You have 16MB of available memory, which is too little for dumping PCAP data.. what system is this?

its ubuntu running inside a proxmox container. i can increase the total memory. whats the minimum memory requirement for running n2disk or how much memory should i allow for the system to use?

**Comment by cardigliano** [comment]
The memory used by n2disk scales based on link speed and available memory, let's say minimum 128MB of available memory

**Comment by abedhossainn** [comment]
> The memory used by n2disk scales based on link speed and available memory, let's say minimum 128MB of available memory

i've increased the total memory of the container. but its still giving the same error.

![image](https://user-images.githubusercontent.com/74364595/99399529-fcf38c80-290f-11eb-9246-fcc760c60480.png)

**Comment by cardigliano** [comment]
This is strange as n2disk is trying to allocate a bit more than 1GB, and you have 4GB available. I need to investigate further to figure out what's going on.

**Comment by abedhossainn** [comment]
> This is strange as n2disk is trying to allocate a bit more than 1GB, and you have 4GB available. I need to investigate further to figure out what's going on.

Thank you. please let me know if you find anything.

**Comment by cardigliano** [comment]
In the meantime you can probably append a new line with "-r" to the configuration file under /etc/n2disk as workaround

**Comment by abedhossainn** [comment]
> In the meantime you can probably append a new line with "-r" to the configuration file under /etc/n2disk as workaround

okay...after adding a new with -r, the system is unable start PF_RING. im sharing the log below.

![image](https://user-images.githubusercontent.com/74364595/99490298-c7908280-2993-11eb-809f-79b04ae48f86.png)

![image](https://user-images.githubusercontent.com/74364595/99490334-d9722580-2993-11eb-9bac-8a51628d5df6.png)

**Comment by cardigliano** [comment]
Are you able to run pfcount in the same system? (pfcount -i eth0)

**Comment by abedhossainn** [comment]
> Are you able to run pfcount in the same system? (pfcount -i eth0)

nope...when i'm trying to install pfring driver(veth) on eth0 interface, the system is saying driver not supported with this error:

**Please provide a supported driver with --configure-driver <name>**

any workaround for that?

**Comment by cardigliano** [comment]
@abedhossainn please note that the pfring kernel module should be loaded on the host system (it is not possible to load the module on the container only)

**Comment by cardigliano** [comment]
@abedhossainn please add --cap-add IPC_LOCK to be able to use Direct IO in n2disk (removing -r)
