### ISSUE TITLE
N2DISK with --disk-limit fails

### ISSUE THREAD

**Issue by Arislen** [ntop/n2disk#35]
Red Hat Enterprise Linux release 8.2 (Ootpa)
Kernel: 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Fri Oct 16 13:38:49 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Versions (installing from https://packages.ntop.org/centos/) :

n2disk x86_64 3.7.201117-5265
pfring x86_64 7.9.0-3273
pfring-dkms noarch 7.9.0-3273
pfring-drivers-zc-dkms noarch 7.9.0-3273
ixgbe-zc noarch 5.5.3.3273-dkms

[trace.log](https://github.com/ntop/n2disk/files/5560189/trace.log)
We are running with licensed N2DISK and PF_RING ZC (ixgbe driver on Intel X520 10G Fiber Card),

Anytime running n2disk with the --disk-limit when the limit is reached n2disk doesn't process any more packets/dump any more pcaps. 

We've have run the command many ways, with different --disk-limits and other options (like CPU thread binding, timeline creation etc) and saving the output to a different disk partition all with the same results.

Test command run:

n2disk -i zc:enp5s0f0 -o /var/log/n2disk  -Q /var/log/n2disk-logs/n2disk-events.log --disk-limit 2% -v --trace-log /tmp/trace.log

Also have to "kill -9" the n2disk process to end it after it reaches/exceeds the 2% limit.

Including the trace output.

**Comment by cardigliano** [comment]
@Arislen I've been able to reproduce this, a new build will be available in a couple of hours at most.
