### ISSUE TITLE
Detect Ookla Application with n2disk snaplen issues

### ISSUE THREAD

**Issue by hungcm95** [ntop/n2disk#37]
Hi. I'm using n2disk and ntopng, followed this article https://www.ntop.org/n2disk/combining-traffic-recording-with-visibility-at-100-gbps/ . It work very well but when I set snaplen to 256 to reduce pcap size, the ntopng cannot detect Speedtest Application flow.

**Comment by cardigliano** [comment]
ntopng requires the full payload to detect the L7 protocol

**Comment by hungcm95** [comment]
Thanks. Is there any option that ntopng read a full payload then save the pcap with snaplen

**Comment by cardigliano** [comment]
@hungcm95 please note that ntopng and n2disk are two different applications, thus you can use different snaplen settings. I thought you were analysing with ntopng pcap data captured with n2disk. Could you provide more details about your configuration?

**Comment by cardigliano** [comment]
Got it. In this case n2disk itself is doing DPI. It can be enhanced to access the full payload for computing the L7 protocol, while dumping to disk the configured snaplen only. However this also depend on the capture mode you are using. What adapter and driver are you using?

**Comment by hungcm95** [comment]
I don't know adapter and driver, I tested on ubuntu server 18.04, it run on VMware

**Comment by cardigliano** [comment]
Closing this as this depends on the configured capture length (the full packet should be captured in order to correctly compute L7 information)
