### ISSUE TITLE
Feature request: Add username to capture log entry

### ISSUE THREAD

**Issue by pbyrne-tpt** [ntop/n2disk#4]
When a capture begins, it would be great to include the initiating user in the log entry. In a multiuser environment, it would be useful to know who started the last dump. 
Thanks!

**Comment by cardigliano** [comment]
n2disk usually runs as a service, thus the user is always 'n2disk' (or the one in the configuration file). Even if you run it in foreground, you need to run it as root (unless you have capture capabilities set).
