### ISSUE TITLE
Segmentation Fault when trying to use Multiple reader threads

### ISSUE THREAD

**Issue by RezaMohammadi99** [ntop/n2disk#40]
I am running n2disk on a super-micro server running Ubuntu 20.04, linux kernel 5.8.0-55-generic. When I try to specify multiple reader threads with core affinities, n2disk crashes and produces a segmentation fault. I have provided the log below. 

 sudo n2disk -R 0,1,2,3 -S 4 -zI 5,6 -C 256 -b 65536 -p 10240 -L -i ntxs1 -o /mnt/storage -e 1
17/Jun/2021 16:47:28 [n2disk.c:6250] [DEBUG] Simulating packet capture
17/Jun/2021 16:47:28 [n2disk.c:6718] Welcome to n2disk v.3.6.210604 (r5261) [CPU 830F1]
17/Jun/2021 16:47:28 [n2disk.c:6751] Running on 2 node(s) system with 64 core(s). NUMA affinity set to node -1.
17/Jun/2021 16:47:28 [n2disk.c:6811] Using PF_RING for packet capture
17/Jun/2021 16:47:28 [n2disk.c:6833] WARNING: If you are using standard drivers (packet capture via kernel) please disable time-pulse thread
17/Jun/2021 16:47:28 [n2disk.c:6836] Multithread support enabled
+ /mnt/storage/1623960090.661315/1623960090.661315.pcap [PCAP 10739563768 bytes][Index 0 bytes][Epoch 1623960090 (1623960090.661315.pcap)]
+ /mnt/storage/1623961285.265396/1623961285.265396.pcap [PCAP 10739563768 bytes][Index 32131965 bytes][Epoch 1623961285 (1623961285.265396.pcap)]
17/Jun/2021 16:47:29 [n2disk.c:6981] Storage /mnt/storage: 20.03 GB in use, 1709.78 GB available (auto-limit set to 1383.85 GB)
17/Jun/2021 16:47:29 [n2disk.c:7031] Storage /mnt/storage limit set to 1383.85 GB, total volume size is 1832.72 GB
17/Jun/2021 16:47:29 [n2disk.c:7078] Dump files max size is set to 10 GB
17/Jun/2021 16:47:29 [n2disk.c:7101] Buffer memory is set to 70 GB (x 7 pcap files)
17/Jun/2021 16:47:29 [n2disk.c:7135] Storage #0 directory: /mnt/storage
17/Jun/2021 16:47:29 [n2disk.c:7153] Up to 100 files will be written per folder
17/Jun/2021 16:47:29 [n2disk.c:7191] Dumping data in 0.2 MB chunks
17/Jun/2021 16:47:46 [n2disk.c:3903] Time pulse thread started
17/Jun/2021 16:47:46 [n2disk.c:5548] WARNING: Running in simulation mode
17/Jun/2021 16:47:47 [n2disk.c:632] n2disk changed user to n2disk
17/Jun/2021 16:47:47 [n2disk.c:2899] Storage /mnt/storage: 20.03 GB in use
17/Jun/2021 16:47:51 [n2disk.c:1335] Caught termination signal 15...
Segmentation fault

PS. Is there documentation on specifying multiple reader threads?

**Comment by cardigliano** [comment]
@RezaMohammadi99 what interface model is ntxs1?
In any case I recommend removing the -R option which is deprecated (it's still there for backward compatibility) and it is not really required.
