### ISSUE TITLE
n2disk license

### ISSUE THREAD

**Issue by Scheppers-wetteren** [ntop/n2disk#46]
I have registered a ntopng Enterprise L license. According to the license generator it should also include a license for n2disk. However, it keeps running in demo and will only capture for 5 min. Did I do something wrong? I'm running ntopng Enterprise L v.5.0.211117 rev.15952 on Ubuntu 20.04.3 LTS.

**Comment by cardigliano** [comment]
Please provide the output of n2disk1g --version (hiding the license key)
