### ISSUE TITLE
probleme when i try to install Ntopng 

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [ntop/n2disk#47]
hi, when i install ntopng for my company i cant start ntop, someone help me pls 
when i start with "service ntopng start "
/usr/local/etc/rc.d/ntopng: WARNING: /usr/local/etc/ntopng.conf is not readable.
/usr/local/etc/rc.d/ntopng: WARNING: failed precmd routine for ntopng

thank for your help

**Comment by cardigliano** [comment]
Please specify the operating system, ntopng version, and any useful info. Please reopen this issue at https://github.com/ntop/ntopng/issues as it's related to ntopng
