### ISSUE TITLE
n2disk latest stable creating timeline directories with incorrect perms on linux

### ISSUE THREAD

**Issue by srfn8kd** [ntop/n2disk#51]
Encountered this after updating to n2disk v.3.6.230206 (r5274)

Perms for new sub directories in the timeline directory are created in an incompatible mode as depicted below, no write is permitted.  Also included the error output which led me to the discovery...

ls -lt /data2/timeline/2023/02/07/
total 0
dr-x-----T 2 n2disk n2disk 10 Feb  7 16:18 16
dr-x-----T 2 n2disk n2disk 10 Feb  7 15:24 15
dr-x-----T 2 n2disk n2disk 10 Feb  7 14:23 14

Feb  7 16:44:20 localhost n2disk[19253]: 07/Feb/2023 16:44:20 [n2disk.c:3216] ERROR: Unable to create timeline links [error=13/Permission denied]
Feb  7 16:44:20 localhost n2disk[19253]: 07/Feb/2023 16:44:20 [n2disk.c:3216] ERROR: Unable to create timeline links [error=13/Permission denied]
Feb  7 16:44:23 localhost n2disk[19253]: 07/Feb/2023 16:44:23 [n2disk.c:3216] ERROR: Unable to create timeline links [error=13/Permission denied]
Feb  7 16:44:23 localhost n2disk[19253]: 07/Feb/2023 16:44:23 [n2disk.c:3216] ERROR: Unable to create timeline links [error=13/Permission denied]

**Comment by cardigliano** [comment]
Please report the OS and provide the n2disk configuration file

**Comment by srfn8kd** [comment]
CentoOS 8Timeline is commented out to temp fix issue--syslog--daemon-i=fbcard:0:b00-P=/var/run/n2disk.pid-o=/data3/pcap/-o=/data2/pcap/#-A=/data2/timeline/--disk-limit=97%-b=16384-p=2048-C=16384-q=1-c=34-w=36,38,44,46--index-3-Z-z=48,50,52,54On Feb 8, 2023, at 00:13, Alfredo Cardigliano ***@***.***> wrote:﻿
Please report the OS and provide the n2disk configuration file

**Comment by srfn8kd** [comment]
I updated this morning to v.3.6.230209 (r5277) and everything looks good, dirs are created with correct perms, thank you for quick resolution, greatly appreciated!

**Comment by cardigliano** [comment]
@srfn8kd please update to latest stable update we released yesterday, it should address this. Please let us know.

**Comment by srfn8kd** [comment]
yes working fine, thank you!On Feb 10, 2023, at 00:42, Alfredo Cardigliano ***@***.***> wrote:﻿
@srfn8kd please update to latest stable update we released yesterday, it should address this. Please let us know.
