### ISSUE TITLE
 linux-headers-6.4.0-060400-generic is not supported

### ISSUE THREAD

**Issue by red2thebones** [ntop/n2disk#53]
Hi, I'm having an issue getting n2disk to work on an Ubuntu Server 22.04 system.
Every time I try to run n2disk, it fails with the following: 

```
"ERROR: Unable to open PF_RING device enp4s0: Address family not supported by protocol [snaplen=1536]
 ERROR: Has the pf_ring kernel module been loaded? Falling back to libpcap.."
```

And when I try to reinstall the PFRING DKMS, I get the following: 

```

Removing old pfring-8.5.0.8415 DKMS files...
Deleting module pfring-8.5.0.8415 completely from the DKMS tree.
Loading new pfring-8.5.0.8415 DKMS files...
Building for 6.4.0-060400-generic
Building for architecture x86_64
Building initial module for 6.4.0-060400-generic
ERROR (dkms apport): kernel package linux-headers-6.4.0-060400-generic is not supported
Error! Bad return status for module build on kernel: 6.4.0-060400-generic (x86_64)
Consult /var/lib/dkms/pfring/8.5.0.8415/build/make.log for more information.
dpkg: error processing package pfring-dkms (--configure):
 installed pfring-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 pfring-dkms
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Any ideas where I can look next?

**Comment by cardigliano** [comment]
@red2thebones it seems you are not running an Ubuntu LTS kernel, your kernel is not currently supported by our drivers

**Comment by red2thebones** [comment]
> @red2thebones it seems you are not running an Ubuntu LTS kernel, your kernel is not currently supported by our drivers

Hello and thank you for your reply. I was under the impression that the version I was running on is LTS (22.04.1 LTS). May I ask if there's any resource I can use to check which version is supported? Thanks again.
