### ISSUE TITLE
 Invalid license found for ***

### ISSUE THREAD

**Issue by FOSquare** [ntop/n2disk#6]
n2disk -h shows：
Welcome to n2disk v.3.1.180604 (r4961) [Nehalem]
Copyright 2009-2018 ntop.org
SystemID: CB78668F7104A212

Then I use CB78668F7104A212 to generate the license file. However when I run 
 ip netns exec 154 n2disk -i eth4 -o /storage -b 1024 -p 512 --di                                                                                    sk-limit 50% -I -A /storage
05/Jun/2018 20:59:08 [n2disk:5664] WARNING: Invalid license found for 339B9EE771                                                                                     04A212
05/Jun/2018 20:59:08 [n2disk:5665] WARNING: (See /etc/n2disk.license) [Missing l                                                                                     icense file]
05/Jun/2018 20:59:08 [n2disk:6177] WARNING: ************************************                                                                                     ***************
05/Jun/2018 20:59:08 [n2disk:6178] WARNING: **                                                                                                                                    **
05/Jun/2018 20:59:08 [n2disk:6179] WARNING: **  Switching to DEMO MODE due to li                                                                                     cense error  **
05/Jun/2018 20:59:08 [n2disk:6180] WARNING: **                                                                                                                                    **
05/Jun/2018 20:59:08 [n2disk:6181] WARNING: ************************************                                                                                     ***************
05/Jun/2018 20:59:08 [n2disk:6182] WARNING: **         Dumping will stop after 5                                                                                      min        **
05/Jun/2018 20:59:08 [n2disk:6184] WARNING: ************************************                                                                                     ***************
05/Jun/2018 20:59:08 [n2disk:6188] Welcome to n2disk v.3.1.180604 (r4961) [Nehal                                                                                     em]
05/Jun/2018 20:59:08 [n2disk:6218] Running on 1 node(s) system with 4 core(s). N                                                                                     UMA affinity set to node -1.
05/Jun/2018 20:59:08 [n2disk:6284] Using PF_RING for packet capture
05/Jun/2018 20:59:08 [n2disk:6313] Multithread support enabled
05/Jun/2018 20:59:08 [n2disk:6426] Storage limit set to 71.07 GB, 0.00 GB are in                                                                                      use, disk size is 142.13 GB
05/Jun/2018 20:59:08 [n2disk:6479] Dump files max size is set to 512 MB
05/Jun/2018 20:59:08 [n2disk:6494] Buffer memory is set to 1024 MB (x 2 pcap fil                                                                                     es)
05/Jun/2018 20:59:08 [n2disk:6534] Using directory /storage for dump files
05/Jun/2018 20:59:08 [n2disk:6552] Up to 100 files will be written per folder
05/Jun/2018 20:59:08 [n2disk:6558] Dump files max duration is set to 600 sec
05/Jun/2018 20:59:08 [n2disk:6598] Dumping data in 0.1 MB chunks
05/Jun/2018 20:59:08 [n2disk:6643] Index processing memory is set to 424 MB (x 2                                                                                      index files)
Killed

Invalid license for 339B9EE77104A212, the system ID is CB78668F7104A212, it is not the same. And at the end, the process is killed.

Thanks a lot.

**Comment by cardigliano** [comment]
@FOSquare, if you run n2disk in a namespace the systemid will change as it is also based on the interfaces in the namespace, please retire your license (https://shop.ntop.org/reset_order_licenses.html) and generate a new one for 339B9EE77104A212

**Comment by cardigliano** [comment]
Please note that n2disk would not work for other namespaces, do you need to run other n2disk instances in other namespaces perhaps?

**Comment by FOSquare** [comment]
1. I retire and regenerate the license, and the problem of license disappeared. I have dual NICs on my server. I would like to have both interfaces works. 

2. when I  run ip netns exec 154 n2disk -i eth4 -o /storage -b 1024 -p 512 -                                                                                     -disk-limit 50% -I -A /storage
"06/Jun/2018 09:33:06 [n2disk:6188] Welcome to n2disk v.3.1.180604 (r4961) [Nehal                                                                                     em]
06/Jun/2018 09:33:06 [n2disk:6218] Running on 1 node(s) system with 4 core(s). N                                                                                     UMA affinity set to node -1.
06/Jun/2018 09:33:06 [n2disk:6284] Using PF_RING for packet capture
06/Jun/2018 09:33:06 [n2disk:6313] Multithread support enabled
06/Jun/2018 09:33:06 [n2disk:6426] Storage limit set to 71.07 GB, 0.00 GB are in                                                                                      use, disk size is 142.13 GB
06/Jun/2018 09:33:06 [n2disk:6479] Dump files max size is set to 512 MB
06/Jun/2018 09:33:06 [n2disk:6494] Buffer memory is set to 1024 MB (x 2 pcap fil                                                                                     es)
06/Jun/2018 09:33:06 [n2disk:6534] Using directory /storage for dump files
06/Jun/2018 09:33:06 [n2disk:6552] Up to 100 files will be written per folder
06/Jun/2018 09:33:06 [n2disk:6558] Dump files max duration is set to 600 sec
06/Jun/2018 09:33:06 [n2disk:6598] Dumping data in 0.1 MB chunks
06/Jun/2018 09:33:06 [n2disk:6643] Index processing memory is set to 424 MB (x 2                                                                                      index files)
Killed"

The process is still killed.

3 when I decrease the buffer size b to 512 and the pcap file length to 218 Mbyte, and run ip netns exec 154 n2disk -i eth4 -o /storage -b 512 -p 218 --disk-limit 30% -I -A /storage
"06/Jun/2018 09:33:36 [n2disk:6188] Welcome to n2disk v.3.1.180604 (r4961) [Nehalem]
06/Jun/2018 09:33:36 [n2disk:6218] Running on 1 node(s) system with 4 core(s). NUMA affinity set to node -1.
06/Jun/2018 09:33:36 [n2disk:6284] Using PF_RING for packet capture
06/Jun/2018 09:33:36 [n2disk:6313] Multithread support enabled
06/Jun/2018 09:33:36 [n2disk:6426] Storage limit set to 42.64 GB, 0.00 GB are in use, disk size is 142.13 GB
06/Jun/2018 09:33:36 [n2disk:6479] Dump files max size is set to 218 MB
06/Jun/2018 09:33:36 [n2disk:6494] Buffer memory is set to 654 MB (x 3 pcap files)
06/Jun/2018 09:33:36 [n2disk:6534] Using directory /storage for dump files
06/Jun/2018 09:33:36 [n2disk:6552] Up to 100 files will be written per folder
06/Jun/2018 09:33:36 [n2disk:6558] Dump files max duration is set to 600 sec
06/Jun/2018 09:33:36 [n2disk:6598] Dumping data in 0.1 MB chunks
06/Jun/2018 09:33:36 [n2disk:6643] Index processing memory is set to 180 MB (x 3 index files)
06/Jun/2018 09:33:37 [n2disk:4540] Using packet timestamps from pf_ring
06/Jun/2018 09:33:37 [n2disk:4582] Using PF_RING v.7.1.0
06/Jun/2018 09:33:37 [n2disk:4592] Dumping traffic statistics on /proc/net/pf_ring/stats/20013-eth4.75
06/Jun/2018 09:33:37 [n2disk:4601] Started PF_RING packet reader thread for device eth4
06/Jun/2018 09:33:37 [n2disk:5065] [reader] Packet capture started
06/Jun/2018 09:33:37 [n2disk:821] n2disk changed user to n2disk"

It was jut stuck here (I did not generate any traffic from/to themis, so eth4 on themis (154) should be idle, I just want to test it works at the beginning).

Thanks a lot.

**Comment by cardigliano** [comment]
@FOSquare you get the "Killed" message when n2disk tries to allocate more memory than what is the available free physical memory in your system, as it needs to lock memory for performance reasons.
As of the second trace, it seems n2disk is running, please check stats from /proc/net/pf_ring/stats/*
BTW, what is the reason you are using namespaces in this case?

**Comment by FOSquare** [comment]
root@aetherD:/proc/net/pf_ring/stats# ls will show empty.
I want to record traffic from interface eth4, and If I use the command without namespace ( n2disk -i eth4 -o /storage -b 512 -p 256 --disk-limit 50% -I -A /storage),  will I record traffic of both interfaces to disk?

And 
ps aux|grep n2disk will show
root     27802  0.0  0.0 126104  2216 pts/2    S+   13:39   0:00 grep n2disk
no n2disk is running I think.   and ps aux|grep pf_ring shows
root     27850  0.0  0.0 126104  2280 pts/2    S+   13:42   0:00 grep pf_ring

Thanks a lot.

**Comment by cardigliano** [comment]
@FOSquare if you run n2disk with -i eth4 it will capture traffic from eth4, not sure if I got your question. Please read /proc/net/pf_ring/stats on the same namespace where n2disk is running (or on the host if you are not running n2disk in a specific namespace).
