### ISSUE TITLE
I tried ip netns exec 154 ls /proc/net/pf_ring/stats. Still show nothing.

### ISSUE THREAD

**Issue by FOSquare** [ntop/n2disk#7]
I can not find the stats file you mentioned. Thanks.

And "ip netns exec 154 ls /proc/net/pf_ring/stats"  also shows nothing. I forgot to mention it last time. sorry for that. However, 
 ip netns exec 154 ls /proc/net/pf_ring/dev/ will show 
eth4 lo

**Comment by cardigliano** [comment]
@FOSquare are you running n2disk in 154? If you are using the dev code from github (or nightly build) you should see a stats file under /proc/net/pf_ring/stats/* while n2disk is running, this is working in our lab.

**Comment by FOSquare** [comment]
Yes.
I did the experiment again. I run ip netns exec 151 iperf -s on node aether.
And ip netns exec 154 iperf -c 192.168.0.151 -t 360 -i 1 on node themis.
Then i run n2disk by " ip netns exec 154 n2disk -i eth4 -o /storage -b 512 -p 256 --disk-limit 30% -I -A /storage"
it shows"
13/Jun/2018 09:01:51 [n2disk:6188] Welcome to n2disk v.3.1.180608 (r4961) [Nehalem]
13/Jun/2018 09:01:51 [n2disk:6218] Running on 1 node(s) system with 4 core(s). NUMA affinity set to node -1.
13/Jun/2018 09:01:51 [n2disk:6284] Using PF_RING for packet capture
13/Jun/2018 09:01:51 [n2disk:6313] Multithread support enabled
13/Jun/2018 09:01:51 [n2disk:6426] Storage limit set to 42.64 GB, 0.00 GB are in use, disk size is 142.13 GB
13/Jun/2018 09:01:51 [n2disk:6479] Dump files max size is set to 256 MB
13/Jun/2018 09:01:51 [n2disk:6494] Buffer memory is set to 512 MB (x 2 pcap files)
13/Jun/2018 09:01:51 [n2disk:6534] Using directory /storage for dump files
13/Jun/2018 09:01:51 [n2disk:6552] Up to 100 files will be written per folder
13/Jun/2018 09:01:51 [n2disk:6558] Dump files max duration is set to 600 sec
13/Jun/2018 09:01:51 [n2disk:6598] Dumping data in 0.1 MB chunks
13/Jun/2018 09:01:51 [n2disk:6643] Index processing memory is set to 212 MB (x 2 index files)
13/Jun/2018 09:01:51 [n2disk:4540] Using packet timestamps from pf_ring
13/Jun/2018 09:01:51 [n2disk:4582] Using PF_RING v.7.1.0
13/Jun/2018 09:01:51 [n2disk:4592] Dumping traffic statistics on /proc/net/pf_ring/stats/31772-eth4.132
13/Jun/2018 09:01:51 [n2disk:4601] Started PF_RING packet reader thread for device eth4
13/Jun/2018 09:01:51 [n2disk:5065] [reader] Packet capture started
13/Jun/2018 09:01:51 [n2disk:821] n2disk changed user to n2disk
13/Jun/2018 09:12:57 [n2disk:542] WARNING: mkdir_p: [path=/storage/1528873906.262415][error=13/Permission denied]
13/Jun/2018 09:12:57 [n2disk:3135] ERROR: Unable to write into file /storage/1528873906.262415/1528873906.262415.pcap.tmp [No such file or directory]
13/Jun/2018 09:12:57 [n2disk:1329] Caught termination signal -1...
13/Jun/2018 09:12:57 [n2disk:1223] [PF_RING] Total stats: 3217691 pkts rcvd/3217691 pkts filtered/0 pkts dropped [0.0%]
13/Jun/2018 09:12:57 [n2disk:1236] [n2disk] Processed 3217691 pkts
13/Jun/2018 09:12:57 [n2disk:1241] Capture Duration:           0:00:11:05:128
13/Jun/2018 09:12:57 [n2disk:1243] Average Capture Throughput: 0.00 Gbit / 0.00 Mpps
13/Jun/2018 09:12:58 [n2disk:5305] Packet capture thread terminated
13/Jun/2018 09:12:58 [n2disk:6976] Reader thread terminated
13/Jun/2018 09:12:58 [n2disk:6995] Writer thread terminated
root@vm1:~# ip netns exec 154 n2disk -i eth4 -o /storage -b 512 -p 256 --disk-limit 30% -I -A /storage
13/Jun/2018 09:28:20 [n2disk:6188] Welcome to n2disk v.3.1.180608 (r4961) [Nehalem]
13/Jun/2018 09:28:20 [n2disk:6218] Running on 1 node(s) system with 4 core(s). NUMA affinity set to node -1.
13/Jun/2018 09:28:20 [n2disk:6284] Using PF_RING for packet capture
13/Jun/2018 09:28:20 [n2disk:6313] Multithread support enabled
13/Jun/2018 09:28:20 [n2disk:6426] Storage limit set to 42.64 GB, 0.00 GB are in use, disk size is 142.13 GB
13/Jun/2018 09:28:20 [n2disk:6479] Dump files max size is set to 256 MB
13/Jun/2018 09:28:20 [n2disk:6494] Buffer memory is set to 512 MB (x 2 pcap files)
13/Jun/2018 09:28:20 [n2disk:6534] Using directory /storage for dump files
13/Jun/2018 09:28:20 [n2disk:6552] Up to 100 files will be written per folder
13/Jun/2018 09:28:20 [n2disk:6558] Dump files max duration is set to 600 sec
13/Jun/2018 09:28:20 [n2disk:6598] Dumping data in 0.1 MB chunks
13/Jun/2018 09:28:20 [n2disk:6643] Index processing memory is set to 212 MB (x 2 index files)
13/Jun/2018 09:28:21 [n2disk:4540] Using packet timestamps from pf_ring
13/Jun/2018 09:28:21 [n2disk:4582] Using PF_RING v.7.1.0
13/Jun/2018 09:28:21 [n2disk:4592] Dumping traffic statistics on /proc/net/pf_ring/stats/31905-eth4.133
13/Jun/2018 09:28:21 [n2disk:4601] Started PF_RING packet reader thread for device eth4
13/Jun/2018 09:28:21 [n2disk:5065] [reader] Packet capture started
13/Jun/2018 09:28:21 [n2disk:821] n2disk changed user to n2disk
13/Jun/2018 09:29:32 [n2disk:542] WARNING: mkdir_p: [path=/storage/1528874901.457614][error=13/Permission denied]
13/Jun/2018 09:29:32 [n2disk:3135] ERROR: Unable to write into file /storage/1528874901.457614/1528874901.457614.pcap.tmp [No such file or directory]
13/Jun/2018 09:29:32 [n2disk:1329] Caught termination signal -1...
13/Jun/2018 09:29:32 [n2disk:1223] [PF_RING] Total stats: 3217931 pkts rcvd/3217931 pkts filtered/0 pkts dropped [0.0%]
13/Jun/2018 09:29:32 [n2disk:1236] [n2disk] Processed 3217931 pkts
13/Jun/2018 09:29:32 [n2disk:1241] Capture Duration:           0:00:01:11:037
13/Jun/2018 09:29:32 [n2disk:1243] Average Capture Throughput: 0.03 Gbit / 0.05 Mpps
13/Jun/2018 09:29:33 [n2disk:5305] Packet capture thread terminated
13/Jun/2018 09:29:33 [n2disk:6976] Reader thread terminated
13/Jun/2018 09:29:33 [n2disk:6995] Writer thread terminated
root@vm1:~# ip netns exec 154 n2disk -i eth4 -o /storage -b 512 -p 256 --disk-limit 30% -I -A /storage
13/Jun/2018 09:30:57 [n2disk:6188] Welcome to n2disk v.3.1.180608 (r4961) [Nehalem]
13/Jun/2018 09:30:57 [n2disk:6218] Running on 1 node(s) system with 4 core(s). NUMA affinity set to node -1.
13/Jun/2018 09:30:57 [n2disk:6284] Using PF_RING for packet capture
13/Jun/2018 09:30:57 [n2disk:6313] Multithread support enabled
13/Jun/2018 09:30:57 [n2disk:6426] Storage limit set to 42.64 GB, 0.00 GB are in use, disk size is 142.13 GB
13/Jun/2018 09:30:57 [n2disk:6479] Dump files max size is set to 256 MB
13/Jun/2018 09:30:57 [n2disk:6494] Buffer memory is set to 512 MB (x 2 pcap files)
13/Jun/2018 09:30:57 [n2disk:6534] Using directory /storage for dump files
13/Jun/2018 09:30:57 [n2disk:6552] Up to 100 files will be written per folder
13/Jun/2018 09:30:57 [n2disk:6558] Dump files max duration is set to 600 sec
13/Jun/2018 09:30:57 [n2disk:6598] Dumping data in 0.1 MB chunks
13/Jun/2018 09:30:57 [n2disk:6643] Index processing memory is set to 212 MB (x 2 index files)
13/Jun/2018 09:30:57 [n2disk:4540] Using packet timestamps from pf_ring
13/Jun/2018 09:30:57 [n2disk:4582] Using PF_RING v.7.1.0
13/Jun/2018 09:30:57 [n2disk:4592] Dumping traffic statistics on /proc/net/pf_ring/stats/31914-eth4.134
13/Jun/2018 09:30:57 [n2disk:4601] Started PF_RING packet reader thread for device eth4
13/Jun/2018 09:30:57 [n2disk:5065] [reader] Packet capture started
13/Jun/2018 09:30:57 [n2disk:821] n2disk changed user to n2disk
"
The above information means the n2disk begin to work and works fine, correct?

Then I use the command "ip netns exec 154 ls /proc/net/pf_ring/stats" I do find file 
31905-eth4.133
Then I use command "" to open the file, the content of the file is 
"Duration:         0:00:00:20:003
Throughput:       0.04 Mpps     0.03 Gbps
Packets:          913588
Filtered:         913588
Dropped:          0
Bytes:            82302768
DumpedBytes:      0
DumpedFiles:      0
SlowSlavesLoops:  0
SlowStorageLoops: 0
LastDumpedEpoch:  0"

The throughput in this file is 0.03Gbps. But the iperf windows shows aournd 2 Gbits/s. What does 0.03Gbps means?

After a short time. the n2disk was terminated. it shows"
.......
13/Jun/2018 09:32:10 [n2disk:542] WARNING: mkdir_p: [path=/storage/1528875057.736988][error=13/Permission denied]
13/Jun/2018 09:32:10 [n2disk:3135] ERROR: Unable to write into file /storage/1528875057.736988/1528875057.736988.pcap.tmp [No such file or directory]
13/Jun/2018 09:32:10 [n2disk:1329] Caught termination signal -1...
13/Jun/2018 09:32:10 [n2disk:1223] [PF_RING] Total stats: 3218190 pkts rcvd/3218190 pkts filtered/0 pkts dropped [0.0%]
13/Jun/2018 09:32:10 [n2disk:1236] [n2disk] Processed 3218190 pkts
13/Jun/2018 09:32:10 [n2disk:1241] Capture Duration:           0:00:01:13:261
13/Jun/2018 09:32:10 [n2disk:1243] Average Capture Throughput: 0.03 Gbit / 0.04 Mpps
13/Jun/2018 09:32:12 [n2disk:5305] Packet capture thread terminated
13/Jun/2018 09:32:12 [n2disk:6976] Reader thread terminated
13/Jun/2018 09:32:12 [n2disk:6995] Writer thread terminated
"
It shows "mkdir" has problems, but I tried the below
root@vm1:/# cd storage/
root@vm1:/storage# mkdir 111.222
root@vm1:/storage# ls
111.222  eth4
mkdir works fine.

When the n2disk is terminated, I check "ip netns exec 154 ls /proc/net/pf_ring/stats" There is no file anymore. That's why I do not find anyting before. 

Since the storge has some problmes. I do not have the storged file currently. Thanks a lot.

**Comment by FOSquare** [comment]
Yes.
I did the experiment again. I run ip netns exec 151 iperf -s on node aether.
And ip netns exec 154 iperf -c 192.168.0.151 -t 360 -i 1 on node themis.
Then i run n2disk by " ip netns exec 154 n2disk -i eth4 -o /storage -b 512 -p 256 --disk-limit 30% -I -A /storage"
it shows"

root@vm1:# ip netns exec 154 n2disk -i eth4 -o /storage -b 512 -p 256 --disk-limit 30% -I -A /storage
13/Jun/2018 09:30:57 [n2disk:6188] Welcome to n2disk v.3.1.180608 (r4961) [Nehalem]
13/Jun/2018 09:30:57 [n2disk:6218] Running on 1 node(s) system with 4 core(s). NUMA affinity set to node -1.
13/Jun/2018 09:30:57 [n2disk:6284] Using PF_RING for packet capture
13/Jun/2018 09:30:57 [n2disk:6313] Multithread support enabled
13/Jun/2018 09:30:57 [n2disk:6426] Storage limit set to 42.64 GB, 0.00 GB are in use, disk size is 142.13 GB
13/Jun/2018 09:30:57 [n2disk:6479] Dump files max size is set to 256 MB
13/Jun/2018 09:30:57 [n2disk:6494] Buffer memory is set to 512 MB (x 2 pcap files)
13/Jun/2018 09:30:57 [n2disk:6534] Using directory /storage for dump files
13/Jun/2018 09:30:57 [n2disk:6552] Up to 100 files will be written per folder
13/Jun/2018 09:30:57 [n2disk:6558] Dump files max duration is set to 600 sec
13/Jun/2018 09:30:57 [n2disk:6598] Dumping data in 0.1 MB chunks
13/Jun/2018 09:30:57 [n2disk:6643] Index processing memory is set to 212 MB (x 2 index files)
13/Jun/2018 09:30:57 [n2disk:4540] Using packet timestamps from pf_ring
13/Jun/2018 09:30:57 [n2disk:4582] Using PF_RING v.7.1.0
13/Jun/2018 09:30:57 [n2disk:4592] Dumping traffic statistics on /proc/net/pf_ring/stats/31914-eth4.134
13/Jun/2018 09:30:57 [n2disk:4601] Started PF_RING packet reader thread for device eth4
13/Jun/2018 09:30:57 [n2disk:5065] [reader] Packet capture started
13/Jun/2018 09:30:57 [n2disk:821] n2disk changed user to n2disk
"
The above information means the n2disk begin to work and works fine, correct?

Then I use the command "ip netns exec 154 ls /proc/net/pf_ring/stats" I do find file
31905-eth4.133
Then I use command "" to open the file, the content of the file is
"Duration: 0:00:00:20:003
Throughput: 0.04 Mpps 0.03 Gbps
Packets: 913588
Filtered: 913588
Dropped: 0
Bytes: 82302768
DumpedBytes: 0
DumpedFiles: 0
SlowSlavesLoops: 0
SlowStorageLoops: 0
LastDumpedEpoch: 0"

The throughput in this file is 0.03Gbps. But the iperf windows shows aournd 2 Gbits/s. What does 0.03Gbps means?

After a short time. the n2disk was terminated. it shows"
.......
13/Jun/2018 09:32:10 [n2disk:542] WARNING: mkdir_p: [path=/storage/1528875057.736988][error=13/Permission denied]
13/Jun/2018 09:32:10 [n2disk:3135] ERROR: Unable to write into file /storage/1528875057.736988/1528875057.736988.pcap.tmp [No such file or directory]
13/Jun/2018 09:32:10 [n2disk:1329] Caught termination signal -1...
13/Jun/2018 09:32:10 [n2disk:1223] [PF_RING] Total stats: 3218190 pkts rcvd/3218190 pkts filtered/0 pkts dropped [0.0%]
13/Jun/2018 09:32:10 [n2disk:1236] [n2disk] Processed 3218190 pkts
13/Jun/2018 09:32:10 [n2disk:1241] Capture Duration: 0:00:01:13:261
13/Jun/2018 09:32:10 [n2disk:1243] Average Capture Throughput: 0.03 Gbit / 0.04 Mpps
13/Jun/2018 09:32:12 [n2disk:5305] Packet capture thread terminated
13/Jun/2018 09:32:12 [n2disk:6976] Reader thread terminated
13/Jun/2018 09:32:12 [n2disk:6995] Writer thread terminated
"
It shows "mkdir" has problems, but I tried the below
root@vm1:/# cd storage/
root@vm1:/storage# mkdir 111.222
root@vm1:/storage# ls
111.222 eth4
mkdir works fine.

When the n2disk is terminated, I check "ip netns exec 154 ls /proc/net/pf_ring/stats" There is no file anymore. That's why I do not find anyting before.

Since the storge has some problmes. I do not have the storged file currently. Thanks a lot.

**Comment by cardigliano** [comment]
Is the data from iperf flowing through eth4? If this is the case, you are probably capturing the received traffic only, while you need transmitted traffic, please take a look at this option:

[--capture-direction|-2] <direction>          | Capture direction: 0=RX+TX, 1=RX only (default), 2=TX only

Please also fix permissions as it seems n2disk cannot write to /storage/ (note n2disk uses the n2disk user, unless you specify a different user with -u <user>)

**Comment by FOSquare** [comment]
Thanks a lot. I fix the problem based on your help. Below is the result. I get very high pkt loss

15/Jun/2018 17:09:58 [n2disk:1223] [PF_RING] Total stats: 6857125 pkts rcvd/6857125 pkts filtered/24306887 pkts dropped [78.0%]
15/Jun/2018 17:09:58 [n2disk:1236] [n2disk] Processed 6857125 pkts
15/Jun/2018 17:09:58 [n2disk:1241] Capture Duration: 0:00:02:01:406
15/Jun/2018 17:09:58 [n2disk:1243] Average Capture Throughput: 0.65 Gbit / 0.06 Mpps

I get 78% pkt loss. The bandwidth of iperf is around 3Gb/s, the capturing is around 0.65Gb/s. considering the pkt loss ratio. The value make sense. The write/read bandwidht of hard disk is around 200MB/s. So have pkt loss is expected. but I would expect pkt loss around 50%, (1 - 200*8/1000/3.0). If I want have zero pkt loss. the only way it to build a RAID controller with hard disk array support. right?

But when I analyze the captured file. I take the first file as an example. there are in total 184788 pkts in 0.85s. the average length is 1414 bytes. The total length of all the pkts is around 
261 MBytes, which is almost the same as the file size 260 MBytes. So those two values make sense. When I calcuate the bandwidht. 260MB*8/0.85 = 3.2Gb/s. It is not 0.65. It means there is no pkt loss since all the 3Gb/s traffic are captured in the file. I was confused. Where is the mistake?

By the way. i was not fully clear to pf_ring zc. Could you explain a little bit more?
I know it is kernel by pass, and will dis-connect the NIC and the kernel. So application that invoke the network stack will not use it meanwhile. So If I want to capture the real traffic on server A, I must use span port to mirror the traffic on NIC of server B. correct? How can I achieve that?
I only know span port on switch before. If this is the case. the user scenarios of pf_ring zc will be limited. What is the real goal for developing pf_ring zc if we can not use it for recording real applications? Or what is the typical application scenario of pf_ring zc? is pr-ring zc only for KVM?

Thanks a lot.

**Comment by cardigliano** [comment]
@FOSquare yes you need a RAID controller or a faster disk, you can check if the disk is actually the bottleneck looking at SlowStorageLoops in /proc/net/pf_ring/stats/* (it should be 0). Please also check the actual traffic rate from proc, as the rate reported by n2disk when you kill it is an avg, not peak.
As of span ports, I was referring to the switch. ZC is meant to be used for monitoring traffic from a network, not from the host itself (which is a special case, and it does not require Zero-Copy capture as the standard driver is able to handle that, as it's the same traffic iperf is generating)
