### ISSUE TITLE
Unable to uninstall Ubuntu package

### ISSUE THREAD

**Issue by loleg** [ntop/n2disk#8]
As reported here: https://askubuntu.com/questions/997820/unable-to-uninstall-package
```
Removing n2disk (3.0.180626-4915) ...
Stopping n2disk services...
update-rc.d: /etc/init.d/n2disk exists during rc.d purge (use -f to force)
dpkg: error processing package n2disk (--remove):
 subprocess installed pre-removal script returned error exit status 1
```

**Comment by cardigliano** [comment]
@loleg please edit /var/lib/dpkg/info/n2disk.prerm and delete this line:

update-rc.d n2disk remove >/dev/null

I pushed a fix, new packages will be available later today.
