### ISSUE TITLE
The interface you are using is not compatible with the 'Light' n2disk license

### ISSUE THREAD

**Issue by drean1968** [ntop/n2disk#9]
I try to start n2disk with the napatech card. I followed the Appendix F from n2disk. I edited the /opt/napatech3/config/ntservice.ini following the documentation. I started the napatech driver and startup the pfring driver.
I give the following command:
[root@localhost scripts]# n2disk -o /data -p 1000 -b 4000 -i nt:1 -q 1 -C 1024 -c 1 -z 2 -w 3 -n 50 -m 100
The result is:
28/Aug/2018 10:49:32 [n2disk.c:6150] Welcome to n2disk v.3.0.180712 (r4916) [CPU 5065]
28/Aug/2018 10:49:32 [n2disk.c:6180] Running on 1 node(s) system with 8 core(s). NUMA affinity set to node 1.
28/Aug/2018 10:49:32 [n2disk.c:6202] ERROR: The interface you are using is not compatible with the 'Light' n2disk license

I don't know how to solve this error.
n2disk --checklicense give LicenseOK.
Please help.

Drean

**Comment by cardigliano** [comment]
@drean1968 could you provide your license and systemid in a private mail?

**Comment by drean1968** [comment]
@cardigliano I can send you the information, but what's your mail address

**Comment by cardigliano** [comment]
Please send to cardigliano@ntop

**Comment by cardigliano** [comment]
This is a "Light" n2disk license which is supposed to work as consumer for Cento XL/XXL only.
